
import { Language } from '../types';

export const dir = (lang: Language) => (lang === Language.FA || lang === Language.AR) ? 'rtl' : 'ltr';

export const translations = {
  [Language.EN]: {
    welcome: "NeuroRehab Login",
    selectUser: "Select Patient",
    newUser: "New Patient",
    createUser: "Create Profile",
    enterName: "Enter name",
    start: "Start Training",
    modules: "Therapy Modules",
    dashboard: "Results & Analysis",
    logout: "Logout",
    level: "Level",
    score: "Score",
    errors: "Errors",
    time: "Time",
    pause: "Pause",
    resume: "Resume",
    stop: "End Session",
    correct: "Correct",
    incorrect: "Incorrect",
    reactionTime: "Reaction Time",
    date: "Date",
    noData: "No training data available yet.",
    exportData: "Export CSV",
    clearData: "Clear History",
    deleteConfirm: "Are you sure? This will permanently delete all training history for this user.",
    about: "About",
    close: "Close",
    back: "Back",
    getReady: "Get Ready...",
    selectProgramDesc: "Select your training program. Consistent practice is key to recovery.",
    exportWord: "Export Report",
    reportIntro: "Patient Report: {name}",
    sagu_ops: {
      rot90: "90° CW",
      rot180: "180°",
      flipH: "Flip Horz",
      flipV: "Flip Vert"
    },
    appDescTitle: "About App",
    appDescription: "NeuroRehab is a professional cognitive rehabilitation platform designed for therapists and patients. It features adaptive training modules targeting Attention, Memory, Executive Functions, and Visual Processing. Inspired by clinical standards like RehaCom.",
    categories: {
      Attention: "Attention",
      Memory: "Memory",
      Executive: "Executive Functions",
      "Visual Field": "Visual Field",
      "Working Memory": "Working Memory"
    },
    stats: {
      totalSessions: "Total Sessions",
      totalTime: "Total Time",
      avgLevel: "Avg Level",
      accuracy: "Accuracy"
    },
    analysis: {
      title: "Clinical Cognitive Profile",
      neuroScore: "Global NeuroScore",
      neuroScoreDesc: "Aggregate cognitive performance index (0-100)",
      strongestDomain: "Strongest Domain",
      needsFocus: "Needs Intervention",
      clinicalNotes: "Clinical Interpretation",
      excellent: "Superior",
      good: "Average",
      fair: "Low Average",
      needsWork: "Impaired",
      insufficient_data: "Insufficient training data to generate a clinical profile. Please complete at least 3 sessions across different modules.",
      intro_good: "The patient demonstrates a generally intact cognitive profile.",
      intro_mixed: "The patient shows a heterogeneous cognitive profile with significant scatter.",
      intro_poor: "Results indicate generalized cognitive deficits requiring comprehensive rehabilitation.",
      impulsivity_warning: "⚠️ High error rate coupled with fast reaction times suggests an impulsive response style. Focus on inhibition tasks (Go/No-Go).",
      slowness_warning: "⚠️ High accuracy with significantly slowed reaction times suggests psychomotor slowing or caution. Encourage faster processing speed.",
      advice_Attention: "Attention deficits detected. Recommended modules: Vigilance (VIGI) and Selective Attention (SACC).",
      advice_Memory: "Memory performance is below baseline. Increase frequency of Verbal Memory (VERB) and Topological Memory (TOPO).",
      advice_Executive: "Executive dysfunction noted. Focus on Planning (PLAN) and Logical Reasoning (LOGI).",
      advice_VisualField: "Visual field scanning is limited. Prioritize Exploration (EXPL) and Visual Field (VIST).",
      advice_WorkingMemory: "Working memory capacity is limited. Daily N-Back and Corsi Block training is advised."
    },
    modInfo: {
      SACC: { name: "Selective Attention", desc: "Focus on specific stimuli while ignoring distractors." },
      DIVI: { name: "Divided Attention", desc: "Multitasking ability with simultaneous visual and auditory stimuli." },
      VIGI: { name: "Vigilance", desc: "Sustained attention over a longer period of time." },
      TOPO: { name: "Topological Memory", desc: "Memorize positions of items in a grid." },
      PHYS: { name: "Physiognomic Memory", desc: "Face recognition and memory training." },
      VERB: { name: "Verbal Memory", desc: "Memorize and recall lists of words." },
      REAK: { name: "Reaction Speed", desc: "Simple reaction time to visual stimuli." },
      LOGI: { name: "Logical Reasoning", desc: "Complete logical sequences and patterns." },
      PLAN: { name: "Planning", desc: "Sequence planning and trail making tasks." },
      SAGU: { name: "Spatial Operations", desc: "Mental rotation and spatial manipulation." },
      CORSI: { name: "Corsi Block", desc: "Visuo-spatial working memory span." },
      NBACK: { name: "N-Back", desc: "Working memory update task." },
      VIST: { name: "Visual Field", desc: "Detection of stimuli in the visual field periphery." },
      EXPL: { name: "Exploration", desc: "Visual scanning and search strategies." },
      NEGT: { name: "Neglect Training", desc: "Training for visual neglect (Line Bisection)." }
    },
    game: {
      sacc_instr: "Find the unique object",
      reak_wait: "Wait...",
      reak_press: "PRESS SPACE!",
      reak_early: "Too Early!",
      reak_instr: "Press Space or Tap as soon as the stimulus appears.",
      corsi_watch: "Watch the sequence",
      corsi_turn: "Your turn",
      corsi_reverse: "REVERSE Order!",
      nback_instr: "Press Match if image is same as {n} step{s} back",
      missed: "Missed!",
      match: "MATCH",
      logi_instr: "Find the missing piece",
      divi_vis: "Click GREEN lights. Ignore RED.",
      divi_aud: "Press button on High (Sharp) Pitch",
      divi_btn: "Respond (Sound)",
      vigi_instr: "Press button ONLY when the lightning bolt appears.",
      detect: "DETECT",
      topo_mem: "Memorize positions",
      topo_where: "Where was this?",
      phys_mem: "Memorize this face",
      phys_which: "Which face did you see?",
      vist_instr: "Click whenever a white dot appears",
      plan_instr: "Connect in order:",
      plan_mode_num: "1 -> 2 -> 3...",
      plan_mode_mix: "1 -> A -> 2 -> B...",
      verb_mem: "Memorize these words",
      verb_recall: "Select the words you saw",
      expl_instr: "Find all matching items:",
      negt_instr: "Click exactly in the CENTER of the bar",
      sagu_instr: "Which image matches the reference operation?"
    },
    words: [
      "Apple", "House", "Car", "Tree", "Book", "Chair", "Dog", "Cat", "Sun", "Moon", 
      "Water", "Bread", "Shoe", "Phone", "Key", "Bird", "Fish", "Flower", "Ball", "Door",
      "Window", "Table", "Pen", "Paper", "Cloud", "Rain", "Snow", "Hand", "Foot", "Eye",
      "Milk", "Coffee", "Tea", "Cake", "Road", "Street", "Park", "Garden", "River", "Sea",
      "Mountain", "Forest", "Star", "Sky", "Fire", "Ice", "Wind", "Sand", "Grass", "Leaf",
      "Hat", "Shirt", "Pants", "Sock", "Bag", "Watch", "Ring", "Glass", "Plate", "Spoon"
    ],
    saveData: "Backup Data",
    loadData: "Restore Data",
    dataImported: "Data restored successfully!",
    errorFile: "Invalid backup file.",
    creator: "Creator: Hossein Nassari - 2025",
    watchVideos: "For educational videos:",
    contactCreator: "Contact Creator:",
    silentModeWarning: "Mobile must not be in silent mode for this test"
  },
  [Language.AR]: {
    welcome: "تسجيل الدخول NeuroRehab",
    selectUser: "اختر المريض",
    newUser: "مريض جديد",
    createUser: "إنشاء ملف",
    enterName: "أدخل الاسم",
    start: "بدء التدريب",
    modules: "وحدات العلاج",
    dashboard: "النتائج والتحليل",
    logout: "خروج",
    level: "المستوى",
    score: "النقاط",
    errors: "الأخطاء",
    time: "الوقت",
    pause: "إيقاف مؤقت",
    resume: "استئناف",
    stop: "إنهاء الجلسة",
    correct: "صحيح",
    incorrect: "خطأ",
    reactionTime: "وقت رد الفعل",
    date: "التاريخ",
    noData: "لا توجد بيانات تدريب متاحة حتى الآن.",
    exportData: "تصدير CSV",
    clearData: "مسح السجل",
    deleteConfirm: "هل أنت متأكد؟ سيتم حذف جميع سجلات التدريب لهذا المستخدم نهائيًا.",
    about: "حول التطبيق",
    close: "إغلاق",
    back: "عودة",
    getReady: "استعد...",
    selectProgramDesc: "اختر برنامج العلاج الخاص بك. الممارسة المستمرة هي مفتاح الشفاء.",
    exportWord: "تصدير التقرير",
    reportIntro: "تقرير المريض: {name}",
    sagu_ops: {
      rot90: "تدوير 90°",
      rot180: "تدوير 180°",
      flipH: "قلب أفقي",
      flipV: "قلب عمودي"
    },
    appDescTitle: "حول التطبيق",
    appDescription: "NeuroRehab هي منصة احترافية لإعادة التأهيل المعرفي مصممة للمعالجين والمرضى. تتميز بوحدات تدريب تكيفية تستهدف الانتباه، الذاكرة، الوظائف التنفيذية، والمعالجة البصرية. مستوحاة من المعايير السريرية.",
    categories: {
      Attention: "الانتباه",
      Memory: "الذاكرة",
      Executive: "الوظائف التنفيذية",
      "Visual Field": "المجال البصري",
      "Working Memory": "الذاكرة العاملة"
    },
    stats: {
      totalSessions: "إجمالي الجلسات",
      totalTime: "إجمالي الوقت",
      avgLevel: "معدل المستوى",
      accuracy: "الدقة"
    },
    analysis: {
      title: "الملف المعرفي السريري",
      neuroScore: "النتيجة العصبية الشاملة",
      neuroScoreDesc: "مؤشر الأداء المعرفي الإجمالي (0-100)",
      strongestDomain: "المجال الأقوى",
      needsFocus: "يحتاج إلى تدخل",
      clinicalNotes: "التفسير السريري",
      excellent: "ممتاز",
      good: "جيد",
      fair: "متوسط",
      needsWork: "ضعيف",
      insufficient_data: "البيانات غير كافية لإنشاء ملف تعريف سريري. يرجى إكمال 3 جلسات على الأقل في وحدات مختلفة.",
      intro_good: "يظهر المريض ملفًا معرفيًا سليمًا بشكل عام.",
      intro_mixed: "يظهر المريض ملفًا معرفيًا غير متجانس مع تفاوت ملحوظ.",
      intro_poor: "تشير النتائج إلى عجز معرفي عام يتطلب إعادة تأهيل شاملة.",
      impulsivity_warning: "⚠️ معدل خطأ مرتفع مع سرعة رد فعل عالية يشير إلى الاندفاع (Impulsivity). يوصى بتمارين التثبيط.",
      slowness_warning: "⚠️ دقة عالية مع رد فعل بطيء جدًا يشير إلى بطء نفسي حركي (Psychomotor Slowing) أو حذر مفرط.",
      advice_Attention: "تم اكتشاف نقص في الانتباه. الوحدات الموصى بها: اليقظة (Vigilance) والانتباه الانتقائي.",
      advice_Memory: "أداء الذاكرة أقل من المعدل. زد من تكرار الذاكرة اللفظية والطوبولوجية.",
      advice_Executive: "لوحظ خلل في الوظائف التنفيذية. ركز على التخطيط (Planning) والاستدلال المنطقي.",
      advice_VisualField: "المسح البصري محدود. أعط الأولوية للاستكشاف (Exploration) والمجال البصري.",
      advice_WorkingMemory: "سعة الذاكرة العاملة محدودة. يوصى بتدريب N-Back و Corsi يوميًا."
    },
    modInfo: {
      SACC: { name: "الانتباه الانتقائي", desc: "التركيز على محفزات محددة وتجاهل المشتتات." },
      DIVI: { name: "الانتباه المقسم", desc: "القدرة على تعدد المهام مع محفزات بصرية وسمعية متزامنة." },
      VIGI: { name: "اليقظة (Vigilance)", desc: "الحفاظ على الانتباه المستمر لفترة طويلة." },
      TOPO: { name: "الذاكرة الطوبولوجية", desc: "تذكر مواقع العناصر في الشبكة." },
      PHYS: { name: "ذاكرة الوجوه", desc: "التعرف على الوجوه وتذكرها." },
      VERB: { name: "الذاكرة اللفظية", desc: "تذكر واستدعاء قوائم الكلمات." },
      REAK: { name: "سرعة رد الفعل", desc: "رد فعل بسيط للمحفزات البصرية." },
      LOGI: { name: "الاستدلال المنطقي", desc: "إكمال المتتاليات والأنماط المنطقية." },
      PLAN: { name: "التخطيط", desc: "تصفية التسلسل ومهام توصيل المسار." },
      SAGU: { name: "العمليات المكانية", desc: "التدوير الذهني والتلاعب المكاني." },
      CORSI: { name: "مكعبات كورسي", desc: "سعة الذاكرة العاملة البصرية المكانية." },
      NBACK: { name: "مهمة N-Back", desc: "تدريب تحديث الذاكرة العاملة." },
      VIST: { name: "المجال البصري", desc: "الكشف عن المحفزات في محيط المجال البصري." },
      EXPL: { name: "الاستكشاف البصري", desc: "المسح البصري واستراتيجيات البحث." },
      NEGT: { name: "تدريب الإهمال", desc: "تدريب للإهمال البصري (تنصيف الخط)." }
    },
    game: {
      sacc_instr: "Find the unique object",
      reak_wait: "Wait...",
      reak_press: "PRESS SPACE!",
      reak_early: "Too Early!",
      reak_instr: "Press Space or Tap as soon as the stimulus appears.",
      corsi_watch: "Watch the sequence",
      corsi_turn: "Your turn",
      corsi_reverse: "REVERSE Order!",
      nback_instr: "Press Match if image is same as {n} step{s} back",
      missed: "Missed!",
      match: "MATCH",
      logi_instr: "Find the missing piece",
      divi_vis: "Click GREEN lights. Ignore RED.",
      divi_aud: "Press button on High (Sharp) Pitch",
      divi_btn: "Respond (Sound)",
      vigi_instr: "Press button ONLY when the lightning bolt appears.",
      detect: "DETECT",
      topo_mem: "Memorize positions",
      topo_where: "Where was this?",
      phys_mem: "Memorize this face",
      phys_which: "Which face did you see?",
      vist_instr: "Click whenever a white dot appears",
      plan_instr: "Connect in order:",
      plan_mode_num: "1 -> 2 -> 3...",
      plan_mode_mix: "1 -> A -> 2 -> B...",
      verb_mem: "Memorize these words",
      verb_recall: "Select the words you saw",
      expl_instr: "Find all matching items:",
      negt_instr: "Click exactly in the CENTER of the bar",
      sagu_instr: "Which image matches the reference operation?"
    },
    words: [
      "Apple", "House", "Car", "Tree", "Book", "Chair", "Dog", "Cat", "Sun", "Moon", 
      "Water", "Bread", "Shoe", "Phone", "Key", "Bird", "Fish", "Flower", "Ball", "Door",
      "Window", "Table", "Pen", "Paper", "Cloud", "Rain", "Snow", "Hand", "Foot", "Eye",
      "Milk", "Coffee", "Tea", "Cake", "Road", "Street", "Park", "Garden", "River", "Sea",
      "Mountain", "Forest", "Star", "Sky", "Fire", "Ice", "Wind", "Sand", "Grass", "Leaf",
      "Hat", "Shirt", "Pants", "Sock", "Bag", "Watch", "Ring", "Glass", "Plate", "Spoon"
    ],
    saveData: "Backup Data",
    loadData: "Restore Data",
    dataImported: "Data restored successfully!",
    errorFile: "Invalid backup file.",
    creator: "Creator: Hossein Nassari - 2025",
    watchVideos: "For educational videos:",
    contactCreator: "Contact Creator:",
    silentModeWarning: "يجب ألا يكون الهاتف في وضع الصامت لهذا الاختبار"
  },
  [Language.FA]: {
    welcome: "ورود به سیستم توانبخشی",
    selectUser: "انتخاب بیمار",
    newUser: "بیمار جدید",
    createUser: "ایجاد پرونده",
    enterName: "نام بیمار",
    start: "شروع تمرین",
    modules: "ماژول‌های درمانی",
    dashboard: "نتایج و تحلیل",
    logout: "خروج",
    level: "سطح",
    score: "امتیاز",
    errors: "خطاها",
    time: "زمان",
    pause: "توقف",
    resume: "ادامه",
    stop: "پایان جلسه",
    correct: "صحيح",
    incorrect: "غلط",
    reactionTime: "زمان واکنش",
    date: "تاریخ",
    noData: "هنوز داده‌ای ثبت نشده است.",
    exportData: "خروجی اکسل (CSV)",
    clearData: "حذف تاریخچه",
    deleteConfirm: "آیا مطمئن هستید؟ تمام سوابق این بیمار حذف خواهد شد.",
    about: "درباره برنامه",
    close: "بستن",
    back: "بازگشت",
    getReady: "...آماده باشید",
    selectProgramDesc: "برنامه درمانی خود را انتخاب کنید. تمرین منظم کلید بهبود است.",
    exportWord: "دانلود گزارش",
    reportIntro: "کاربر گرامی {name} عزیز، گزارش عملکرد شما به شرح زیر می‌باشد",
    sagu_ops: {
      rot90: "چرخش ۹۰ درجه",
      rot180: "چرخش ۱۸۰ درجه",
      flipH: "قرینه افقی",
      flipV: "قرینه عمودی"
    },
    appDescTitle: "درباره برنامه",
    appDescription: "نوروریهب (NeuroRehab) یک پلتفرم تخصصی توانبخشی شناختی است که برای درمانگران و بیماران طراحی شده است. این برنامه شامل ماژول‌های تطبیقی برای تقویت توجه، حافظه، عملکردهای اجرایی و پردازش بینایی می‌باشد.",
    categories: {
      Attention: "توجه و تمرکز",
      Memory: "حافظه",
      Executive: "عملکردهای اجرایی",
      "Visual Field": "میدان دید",
      "Working Memory": "حافظه کاری"
    },
    stats: {
      totalSessions: "کل جلسات",
      totalTime: "زمان کل",
      avgLevel: "میانگین سطح",
      accuracy: "دقت"
    },
    analysis: {
      title: "پروفایل شناختی بالینی",
      neuroScore: "نمره عصبی-شناختی (NeuroScore)",
      neuroScoreDesc: "شاخص جامع عملکرد شناختی (۰-۱۰۰)",
      strongestDomain: "نقطه قوت",
      needsFocus: "نیاز به مداخله",
      clinicalNotes: "تفسیر بالینی سیستم",
      excellent: "عالی",
      good: "خوب",
      fair: "متوسط",
      needsWork: "نیاز به تلاش",
      insufficient_data: "داده‌های تمرینی برای ایجاد پروفایل بالینی کافی نیست. لطفاً حداقل ۳ جلسه در حیطه‌های مختلف انجام دهید.",
      intro_good: "بیمار یک پروفایل شناختی منسجم و بالاتر از حد انتظار نشان می‌دهد.",
      intro_mixed: "پروفایل بیمار ناهمگن است و نوسانات عملکردی قابل توجهی بین حوزه‌ها دیده می‌شود.",
      intro_poor: "نتایج نشان‌دهنده نقص‌های شناختی عمومی است که نیاز به توانبخشی جامع دارد.",
      impulsivity_warning: "⚠️ نرخ خطای بالا همراه با سرعت واکنش سریع، بیانگر الگوی «تکانشگری» (Impulsivity) است. تمرینات بازداری توصیه می‌شود.",
      slowness_warning: "⚠️ دقت بالا همراه با کندی واکنش، احتمال «کندی روانی-حرکتی» (Psychomotor Slowing) یا احتیاط بیش از حد را مطرح می‌کند.",
      advice_Attention: "نقص در توجه مشاهده شد. تمرکز بر ماژول‌های Vigilance و Selective Attention پیشنهاد می‌شود.",
      advice_Memory: "عملکرد حافظه پایین‌تر از سطح انتظار است. تمرینات Verbal و Topological را افزایش دهید.",
      advice_Executive: "اختلال در کارکردهای اجرایی. تمرینات Planning و Logic اولویت دارند.",
      advice_VisualField: "اسکن بینایی محدود است. ماژول‌های Exploration و Visual Field توصیه می‌شوند.",
      advice_WorkingMemory: "ظرفیت حافظه کاری محدود است. تمرین روزانه N-Back و Corsi ضروری است."
    },
    modInfo: {
      SACC: { name: "توجه انتخابی", desc: "تمرکز بر محرک خاص و نادیده گرفتن عوامل مزاحم." },
      DIVI: { name: "توجه تقسیم‌شده", desc: "انجام همزمان دو تکلیف (بینایی و شنوایی)." },
      VIGI: { name: "هوشیاری (Vigilance)", desc: "حفظ توجه پایدار در طول زمان." },
      TOPO: { name: "حافظه توپولوژیک", desc: "به‌خاطر سپردن موقعیت مکانی آیتم‌ها." },
      PHYS: { name: "حافظه چهره", desc: "بازشناسی و یادآوری چهره‌ها." },
      VERB: { name: "حافظه کلامی", desc: "به‌خاطر سپردن و یادآوری لیست کلمات." },
      REAK: { name: "سرعت واکنش", desc: "واکنش سریع به محرک‌های بصری." },
      LOGI: { name: "استدلال منطقی", desc: "تکمیل الگوها و دنباله‌های منطقی." },
      PLAN: { name: "برنامه‌ریزی", desc: "توانایی برنامه‌ریزی و دنبال کردن توالی‌ها." },
      SAGU: { name: "عملیات فضایی", desc: "چرخش ذهنی اشکال و تجسم فضایی." },
      CORSI: { name: "تکلیف کورسی", desc: "سنجش حافظه کاری دیداری-فضایی." },
      NBACK: { name: "تکلیف N-Back", desc: "تمرین به‌روزرسانی حافظه کاری." },
      VIST: { name: "میدان دید", desc: "تشخیص محرک‌ها در محیط پیرامونی." },
      EXPL: { name: "اکتشاف بصری", desc: "جستجو و اسکن محیطی." },
      NEGT: { name: "تمرین غفلت در بینایی", desc: "تمرین برای بیماران دارای Neglect (خط‌زنی)." }
    },
    game: {
      sacc_instr: "شکل منحصر‌به‌فرد را پیدا کنید",
      reak_wait: "صبر کنید...",
      reak_press: "ضربه بزنید!",
      reak_early: "خیلی زود!",
      reak_instr: "به محض دیدن محرک، کلید فاصله یا صفحه را لمس کنید.",
      corsi_watch: "به ترتیب دقت کنید",
      corsi_turn: "نوبت شماست",
      corsi_reverse: "ترتيب معکوس!",
      nback_instr: "اگر تصویر با {n} مرحله قبل یکسان بود، دکمه را بزنید",
      missed: "جا افتاد!",
      match: "تطبیق",
      logi_instr: "قطعه گمشده را پیدا کنید",
      divi_vis: "دایره‌های سبز را بزنید. قرمز را نزنید.",
      divi_aud: "با شنیدن صدای «زیر» (تیز) دکمه را بزنید",
      divi_btn: "پاسخ (صدا)",
      vigi_instr: "فقط زمانی که «رعد و برق» دیدید دکمه را بزنید.",
      detect: "تشخیص",
      topo_mem: "مکان‌ها را به خاطر بسپارید",
      topo_where: "این آیتم کجا بود؟",
      phys_mem: "این چهره را به خاطر بسپارید",
      phys_which: "کدام چهره را دیدید؟",
      vist_instr: "هرگاه نقطه سفید دیدید کلیک کنید",
      plan_instr: "به ترتیب وصل کنید:",
      plan_mode_num: "1 -> 2 -> 3...",
      plan_mode_mix: "1 -> A -> 2 -> B...",
      verb_mem: "کلمات را به خاطر بسپارید",
      verb_recall: "کلماتی که دیدید را انتخاب کنید",
      expl_instr: "تمام موارد مشابه این شکل را پیدا کنید:",
      negt_instr: "دقیقاً وسط خط کلیک کنید",
      sagu_instr: "تصویر حاصل از عملیات نشان داده شده کدام است؟"
    },
    words: [
      "سیب", "خانه", "ماشین", "درخت", "کتاب", "صندلی", "سگ", "گربه", "خورشید", "ماه", 
      "آب", "نان", "کفش", "تلفن", "کلید", "پرنده", "ماهی", "گل", "توپ", "در",
      "پنجره", "میز", "خودکار", "کاغذ", "ابر", "باران", "برف", "دست", "پا", "چشم",
      "شیر", "قهوه", "چای", "کیک", "جاده", "خیابان", "پارک", "باغ", "رودخانه", "دریا",
      "کوه", "جنگل", "ستاره", "آسمان", "آتش", "یخ", "باد", "شن", "چمن", "برگ",
      "کلاه", "پیراهن", "شلوار", "جوراب", "کیف", "ساعت", "انگشتر", "لیوان", "بشقاب", "قاشق"
    ],
    saveData: "ذخیره اطلاعات",
    loadData: "فراخوانی اطلاعات",
    dataImported: "اطلاعات با موفقیت بازیابی شد!",
    errorFile: "فایل پشتیبان نامعتبر است.",
    creator: "سازنده حسین نصاری سال ۱۴۰۴",
    watchVideos: "جهت دسترسی به ویدئوهای آموزشی:",
    contactCreator: "ارتباط با سازنده:",
    silentModeWarning: "برای این تست موبایل نباید روی حالت سایلنت باشد"
  }
};
